/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'assignment';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BACKARROW = 'assets/images/backArrow.svg';
  static const String CARD1 = 'assets/images/card1.png';
  static const String CARD2 = 'assets/images/card2.png';
  static const String CARD3 = 'assets/images/card3.png';
  static const String CARD4 = 'assets/images/card4.png';
  static const String CARD5 = 'assets/images/card5.png';
  static const String CARD6 = 'assets/images/card6.png';
  static const String CAROUSEL_IMAGE = 'assets/images/carousel_image.png';
  static const String CATEGORY1 = 'assets/images/category1.png';
  static const String CATEGORY2 = 'assets/images/category2.png';
  static const String CATEGORY3 = 'assets/images/category3.png';
  static const String CATEGORY4 = 'assets/images/category4.png';
  static const String COPY = 'assets/images/copy.svg';
  static const String DETAILIMAGE = 'assets/images/detailImage.png';
  static const String DROPARROW = 'assets/images/dropArrow.svg';
  static const String FACEBOOK = 'assets/images/facebook.svg';
  static const String FILTER = 'assets/images/filter.svg';
  static const String FIRE = 'assets/images/fire.svg';
  static const String IMAGE1 = 'assets/images/image1.png';
  static const String IMAGE2 = 'assets/images/image2.png';
  static const String IMAGE3 = 'assets/images/image3.png';
  static const String IMAGE4 = 'assets/images/image4.png';
  static const String PERSON1 = 'assets/images/person1.png';
  static const String RESTAURANT = 'assets/images/restaurant.png';
  static const String TWITTER = 'assets/images/twitter.svg';
  static const String WHATSAPP = 'assets/images/whatsapp.svg';
}
